// Firebase Configuration
// This file is auto-generated during the build process
// DO NOT edit this file manually - it will be overwritten

const firebaseConfig = {
    "apiKey": "AIzaSyAcscqKXw5rWd3YpqTHH7Lss2sUFKblBKk",
    "authDomain": "basedatos-57052.firebaseapp.com",
    "projectId": "basedatos-57052",
    "storageBucket": "basedatos-57052.firebasestorage.app",
    "messagingSenderId": "1041816516368",
    "appId": "1:1041816516368:web:5dd2e417863ccef5d95795"
};

// Export the configuration
export { firebaseConfig };
